spring:
  application:
    name: notification-service
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:35432/postgres}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    open-in-view: false
    show-sql: true
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
    ############# Mail Properties ###########
  mail:
    host: ${MAIL_HOST:127.0.0.1}
    port: ${MAIL_PORT:1025}
    username: ${MAIL_USERNAME:PLACEHOLDER}
    password: ${MAIL_PASSWORD:PLACEHOLDER}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8083
  shutdown: graceful
management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    git:
      mode: full

logging:
  level:
    root: INFO
    org.springframework.test.context.jdbc: DEBUG
    org.springframework.jdbc.datasource.init: DEBUG
  pattern:
    console: "%d{HH:mm:ss} [%-5level] %logger{36} - %msg%n"

######## Notifications Service Configuration  #########
notifications:
  support-email: zahir_wp@yahoo.ca
#  catalog-service-url: http://localhost:8081
  order-events-exchange: orders-exchange
  new-orders-queue: new-orders
  delivered-orders-queue: delivered-orders
  cancelled-orders-queue: cancelled-orders
  error-orders-queue: error-orders


